[package]
name = "nes-emulator"
version = "1.0.0"
edition = "2021"

# generic Result<> with any error
[dependencies.anyhow]
version = "1.0.75"

# random number generator
[dependencies.rand]
version = "0.8.5"

# Simple DirectMedia Layer bindings
[dependencies.sdl2]
version = "0.36.0"
default-features = false
features = ["ttf"]

# hashmap! literal macro
[dependencies.maplit2]
version = "1.0.5"

# iter extensions
[dependencies.itertools]
version = "0.12.0"

# Linux system API bindings
[dependencies.nix]
version = "0.27.1"
default-features = false
features = ["time"]

# String.substring()
[dependencies.substring]
version = "1.4.5"

# CPAL Cross Platform Audio Library
[dependencies.cpal]
version = "0.15.2"

# Enum utils
[dependencies.strum]
version = "0.25.0"
[dependencies.strum_macros]
version = "0.25.3"